on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Duet Web Control
        uses: actions/checkout@v4
        with:
          repository: Duet3D/DuetWebControl
          ref: v3.6.0-rc.3
          path: dwc-build

      - name: Build release asset
        run: |
          dist/release.sh mos-release-${{ github.ref_name }}

      - name: Build MillenniumOS UI Release
        run: |
          cp -r ui/* dwc-build/
          cp -r ui/sd dwc-build/src/plugins/MillenniumOS/
          cd dwc-build
          ./src/plugins/MillenniumOS/dist/release.sh
          cp dist/MillenniumOS-*.zip ../dist/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: MillenniumOS ${{ github.ref_name }}
          draft: true
          generate_release_notes: true
          files: |
            dist/mos-release-${{ github.ref_name }}.zip
            dist/MillenniumOS-*.zip
            dist/millennium-os.cps
            dist/millennium_os_post.py
            dist/milo-v1.5-std.mch
