on:
  push:
    tags:
      - 'v*'

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build release asset
        run: |
          dist/release.sh mos-release-${{ github.ref_name }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: MillenniumOS ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: true
          prerelease: false
      - name: Upload Release Zip
        id: upload-mos-zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/mos-release-${{ github.ref_name }}.zip
          asset_name: mos-release-${{ github.ref_name }}.zip
          asset_content_type: application/zip

      - name: Upload F360 Post-processor
        id: upload-f360-post
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/millennium-os.cps
          asset_name: millennium-os-${{ github.ref_name }}-post-f360.cps
          asset_content_type: application/octet-stream

      - name: Upload F360 Standard Machine Definition
        id: upload-f360-mch-std
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/milo-v1.5-std.mch
          asset_name: milo-v1.5-std-${{ github.ref_name }}.mch
          asset_content_type: application/octet-stream

      - name: Upload F360 FMJ Machine Definition
        id: upload-f360-mch-fmj
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/milo-v1.5-120mm-z.mch
          asset_name: milo-v1.5-120mm-z-${{ github.ref_name }}.mch
          asset_content_type: application/octet-stream